spring:
    application:
        name: wedding-planner
    mail:
      host: smtp.gmail.com
      port: 587
      username: sharadamarasinha@gmail.com
      password: xsqx jkrf heue bwnx
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true

server:
    port: 8082
    error:
      include-message: always

jwt:
  secret: "your-256-bit-secret-key-must-be-at-least-32-chars-long"
  expiration: 86400

logging:
  level:
    org.springframework.jdbc.core: DEBUG       # Logs SQL queries
    org.springframework.jdbc.core.StatementCreatorUtils: TRACE  # Logs parameter bindings
